language: objective-c
osx_image: xcode11

install:
  - bash ./scripts/install.sh

script:
  - bash ./scripts/build_loop.dev.sh Debug
  #TODO: require critial alerts to be by-passed for loop for tests to run on simulator
  #- ./node_modules/.bin/detox e2e/smoke_test -c ios.sim.release --headless --cleanup